$(document).ready(function(){
  //testLog
  var chuck = function(x){console.log(x);} 
  var vocabsTable = $('table'),thead =$('thead'),tbody=$('tbody');
  var colArray = [];
  
  var theadElements = ['word','meaning','sound','class','category','memo','example'];
  var bgImgIndex,randomIndex,bgImgAry=['Sea','Light','Green','Soft','Color','Organic','Unique','Cold','Autumn'];
  for(var i=0;i<bgImgAry.length;i++){bgImgAry[i] = 'images\/bgImg'+bgImgAry[i]+'.png'}
  var vocabs = [
    {
      'level':'2',
      'word':'красный',
      'sound':'krasnyy',
      'meaning':'red',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'синий',
      'sound':'siniy',
      'meaning':'blue',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'зеленый',
      'sound':'zelenyy',
      'meaning':'green',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'желтый',
      'sound':'zheltyy',
      'meaning':'yellow',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'розовый',
      'sound':'rozovyy',
      'meaning':'pink',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'фиолетовый',
      'sound':'fioletovyy',
      'meaning':'purple',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'белый',
      'sound':'belyy',
      'meaning':'white',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'черный',
      'sound':'chernyy',
      'meaning':'black',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'коричневый',
      'sound':'korichnevyy',
      'meaning':'brown',
      'class':'adjective',
      'category':'color',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'я',
      'sound':'ya',
      'meaning':'I',
      'class':'pronoun',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'ты',
      'sound':'ty',
      'meaning':'you',
      'class':'pronoun',
      'category':'word',
      'memo':'singular',
      'example':''
    },
    {
      'level':'1',
      'word':'вы',
      'sound':'vy',
      'meaning':'you',
      'class':'pronoun\(p\)',
      'category':'word',
      'memo':'multiple',
      'example':''
    },
    {
      'level':'1',
      'word':'он',
      'sound':'on',
      'meaning':'he',
      'class':'pronoun\(m\)',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'она',
      'sound':'ona',
      'meaning':'she',
      'class':'pronoun\(f\)',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'они',
      'sound':'oni',
      'meaning':'they',
      'class':'pronoun\(p\)',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'тот',
      'sound':'tot',
      'meaning':'that',
      'class':'pronoun',
      'category':'word',
      'memo':'demonstrative pronoun',
      'example':''
    },
    {
      'level':'3',
      'word':'который',
      'sound':'kotoryy',
      'meaning':'which',
      'class':'pronoun',
      'category':'word',
      'memo':'demonstrative pronoun',
      'example':''
    },
    {
      'level':'2',
      'word':'так',
      'sound':'tak',
      'meaning':'such',
      'class':'pronoun',
      'category':'word',
      'memo':'demonstrative pronoun',
      'example':''
    },
    {
      'level':'1',
      'word':'а',
      'sound':'a',
      'meaning':'and',
      'class':'conjunction',
      'category':'word',
      'memo':'sometime this means \"but\".',
      'example':''
    },
    {
      'level':'3',
      'word':'автобус',
      'sound':'avtobus',
      'meaning':'bus',
      'class':'noun\(m\)',
      'category':'traffic',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'автор',
      'sound':'avtor',
      'meaning':'author',
      'class':'noun\(m\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'агроном',
      'sound':'agronom',
      'meaning':'agriculture scholar',
      'class':'noun\(m\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'6',
      'word':'ангина',
      'sound':'angina',
      'meaning':'tonsillitis',
      'class':'noun\(m\)',
      'category':'disease',
      'memo':'= тонзиллит',
      'example':''
    },
    {
      'level':'5',
      'word':'аппетит',
      'sound':'appetit',
      'meaning':'appetite',
      'class':'noun\(m\)',
      'category':'food',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'апрель',
      'sound':'aprely',
      'meaning':'april',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'month',
      'example':''
    },
    {
      'level':'4',
      'word':'артист',
      'sound':'arrtist',
      'meaning':'artist',
      'class':'noun\(m\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'артистка',
      'sound':'arrtistka',
      'meaning':'artist',
      'class':'noun\(f\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'6',
      'word':'атомный',
      'sound':'atomnyy',
      'meaning':'atomic',
      'class':'adjective',
      'category':'science',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'аудитория',
      'sound':'auditoriya',
      'meaning':'classroom',
      'class':'noun\(f\)',
      'category':'school',
      'memo':'bigger than класс ',
      'example':''
    },
    {
      'level':'4',
      'word':'аэропорт',
      'sound':'aeroport',
      'meaning':'airport',
      'class':'noun\(m\)',
      'category':'traffic',
      'memo':'≒ аэродром',
      'example':''
    },
    {
      'level':'3',
      'word':'бабушка',
      'sound':'babushka',
      'meaning':'grandmother',
      'class':'noun\(f\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'балет',
      'sound':'balet',
      'meaning':'bellet',
      'class':'noun\(m\)',
      'category':'sport',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'банка',
      'sound':'banka',
      'meaning':'container',
      'class':'noun\(f\)',
      'category':'life',
      'memo':'cylinder like bottles or cans',
      'example':''
    },
    {
      'level':'2',
      'word':'без',
      'sound':'bez',
      'meaning':'without',
      'class':'preposition',
      'category':'word',
      'memo':'rq.accusative case',
      'example':''
    },
    {
      'level':'5',
      'word':'безопасность',
      'sound':'bizopasnast\'',
      'meaning':'safety',
      'class':'noun\(m\)',
      'category':'',
      'memo':'без+онасно',
      'example':''
    },
    {
      'level':'4',
      'word':'безопасный',
      'sound':'bizopasnyy',
      'meaning':'safe',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'безсловно',
      'sound':'bezslovna',
      'meaning':'absolutely',
      'class':'adverb',
      'category':'',
      'memo':'≒ абсолютно',
      'example':''
    },
    {
      'level':'4',
      'word':'берег',
      'sound':'berek',
      'meaning':'shore',
      'class':'noun\(m\)',
      'category':'nature',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'библиотека',
      'sound':'biblioteka',
      'meaning':'library',
      'class':'noun\(f\)',
      'category':'facility',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'билет',
      'sound':'bilet',
      'meaning':'ticket',
      'class':'noun\(m\)',
      'category':'life',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'бифштекс',
      'sound':'bifshteks',
      'meaning':'steak',
      'class':'noun\(m\)',
      'category':'food',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'благодарить',
      'sound':'blagodarit\'',
      'meaning':'appreciate',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'более',
      'sound':'boleye',
      'meaning':'more',
      'class':'adverb',
      'category':'',
      'memo':'prepend to adjective or adverb',
      'example':''
    },
    {
      'level':'3',
      'word':'болезнь',
      'sound':'bolezn\'',
      'meaning':'disease',
      'class':'noun\(f\)',
      'category':'disease',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'болен',
      'sound':'bolen',
      'meaning':'short',
      'class':'adjective\(s\)',
      'category':'',
      'memo':'.',
      'example':''
    },
    {
      'level':'4',
      'word':'болеть',
      'sound':'bolet\'',
      'meaning':'get sick',
      'class':'verb\(Ⅱ\)',
      'category':'life',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'больна',
      'sound':'bol\'na',
      'meaning':'sick',
      'class':'adjective\(s\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'больной',
      'sound':'bol\'noy',
      'meaning':'sick',
      'class':'adjective',
      'category':'',
      'memo':'this also means someone in sick',
      'example':''
    },
    {
      'level':'3',
      'word':'больше',
      'sound':'bol\'she',
      'meaning':'more',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'большой',
      'sound':'bol\'shoy',
      'meaning':'big',
      'class':'adjective',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'бояться',
      'sound':'boyat\'sya',
      'meaning':'fear',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'брат',
      'sound':'brat',
      'meaning':'brother',
      'class':'noun\(m\)',
      'category':'family',
      'memo':'plural->братья',
      'example':''
    },
    {
      'level':'4',
      'word':'брать',
      'sound':'brat\'',
      'meaning':'take',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-беру,берёшь',
      'example':''
    },
    {
      'level':'6',
      'word':'бриться',
      'sound':'brit\'sya',
      'meaning':'shave',
      'class':'verb\(Ⅱ\)',
      'category':'life',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'броситься',
      'sound':'brasit\'sya',
      'meaning':'jump into',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'булка',
      'sound':'bulka',
      'meaning':'French bread',
      'class':'noun\(f\)',
      'category':'food',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'бумага',
      'sound':'bumaga',
      'meaning':'paper',
      'class':'noun\(f\)',
      'category':'material',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'бутылка',
      'sound':'butilka',
      'meaning':'bottle',
      'class':'noun\(f\)',
      'category':'food',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'буфет',
      'sound':'bufet',
      'meaning':'buffet',
      'class':'noun\(m\)',
      'category':'facility',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'быстро',
      'sound':'bystro',
      'meaning':'quickly',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'быть',
      'sound':'byt\'',
      'meaning':'be',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'в',
      'sound':'v',
      'meaning':'in',
      'class':'preposition',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'вагон',
      'sound':'vagon',
      'meaning':'wagon',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'важно',
      'sound':'vazhno',
      'meaning':'impotantly',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'ваза',
      'sound':'vaza',
      'meaning':'vase',
      'class':'noun\(f\)',
      'category':'furniture',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'ваш',
      'sound':'vash',
      'meaning':'your',
      'class':'pronoun',
      'category':'',
      'memo':'plural',
      'example':''
    },
    {
      'level':'4',
      'word':'вдруг',
      'sound':'fdruk',
      'meaning':'suddenly',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'везде',
      'sound':'vezde',
      'meaning':'everywhere',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'верность',
      'sound':'vernost\'',
      'meaning':'honesty',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'вернуться',
      'sound':'vernut\'sya',
      'meaning':'return',
      'class':'verb\(e\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'верный',
      'sound':'vernyy',
      'meaning':'honest',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'весело',
      'sound':'vesilo',
      'meaning':'hilarious',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'весёлый',
      'sound':'visholyy',
      'meaning':'hilarious',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'весна',
      'sound':'visna',
      'meaning':'spring',
      'class':'noun\(f\)',
      'category':'',
      'memo':'season',
      'example':''
    },
    {
      'level':'3',
      'word':'весной',
      'sound':'visnoy',
      'meaning':'spring',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'вести',
      'sound':'vesti',
      'meaning':'lead',
      'class':'verb\(e\)',
      'category':'',
      'memo':'motion verbs.',
      'example':''
    },
    {
      'level':'2',
      'word':'весь',
      'sound':'ves\'',
      'meaning':'all',
      'class':'adjective',
      'category':'word',
      'memo':'-вся,всё,все',
      'example':''
    },
    {
      'level':'3',
      'word':'ветер',
      'sound':'veter',
      'meaning':'wind',
      'class':'noun\(m\)',
      'category':'nature',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'вечер',
      'sound':'vecher',
      'meaning':'evening',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'вечером',
      'sound':'vecherom',
      'meaning':'in the evening',
      'class':'adverb',
      'category':'time',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'взрослый',
      'sound':'vzroslyy',
      'meaning':'adult',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'взять',
      'sound':'vzyat\'',
      'meaning':'take',
      'class':'varb\(e\)',
      'category':'',
      'memo':'-возьму,возьмёшь',
      'example':''
    },
    {
      'level':'3',
      'word':'видеть',
      'sound':'videt\'',
      'meaning':'see',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-вижу',
      'example':''
    },
    {
      'level':'5',
      'word':'владеть',
      'sound':'vladet\'',
      'meaning':'master',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'влияние',
      'sound':'vliyaniye',
      'meaning':'effect',
      'class':'noun\(n\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'вместе',
      'sound':'vmeste',
      'meaning':'together',
      'class':'adverb',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'внимание',
      'sound':'vnimaniye',
      'meaning':'attention',
      'class':'noun\(n\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'внимательно',
      'sound':'vnimatel\'no',
      'meaning':'carefully',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'внук',
      'sound':'vnuk',
      'meaning':'grandson',
      'class':'noun\(m\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'внутри',
      'sound':'vnutry',
      'meaning':'within',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'внучка',
      'sound':'vnuchka',
      'meaning':'granddaughter',
      'class':'noun\(f\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'вовремя',
      'sound':'vovremya',
      'meaning':'on time',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'вода',
      'sound':'voda',
      'meaning':'water',
      'class':'noun\(f\)',
      'category':'nature',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'водить',
      'sound':'vodit\'',
      'meaning':'lead',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-вожу',
      'example':''
    },
    {
      'level':'4',
      'word':'возле',
      'sound':'vozle',
      'meaning':'near',
      'class':'preposition',
      'category':'',
      'memo':'rq. accusative case',
      'example':''
    },
    {
      'level':'3',
      'word':'войти',
      'sound':'voyti',
      'meaning':'enter',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-войду,войдёшь',
      'example':''
    },
    {
      'level':'3',
      'word':'вокзал',
      'sound':'vokzal',
      'meaning':'station',
      'class':'\(\)',
      'category':'',
      'memo':'bigger than станция',
      'example':''
    },
    {
      'level':'5',
      'word':'волновать',
      'sound':'volnovat\'',
      'meaning':'excite disturb agitate',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'волос',
      'sound':'volos',
      'meaning':'hair',
      'class':'noun\(m\)',
      'category':'human body',
      'memo':'generally plural',
      'example':''
    },
    {
      'level':'2',
      'word':'воскресенье',
      'sound':'voskresen\'ye',
      'meaning':'sunday',
      'class':'noun\(n\)',
      'category':'time',
      'memo':'week',
      'example':''
    },
    {
      'level':'3',
      'word':'восток',
      'sound':'vostok',
      'meaning':'east',
      'class':'noun\(m\)',
      'category':'direction',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'вот',
      'sound':'vot',
      'meaning':'here it is',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'впадать',
      'sound':'vpadat\'',
      'meaning':'fall',
      'class':'verb',
      'category':'',
      'memo':'в+падать',
      'example':''
    },
    {
      'level':'3',
      'word':'врач',
      'sound':'vrach',
      'meaning':'doctor',
      'class':'noun\(m\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'время',
      'sound':'vremya',
      'meaning':'time',
      'class':'noun\(n\)',
      'category':'time',
      'memo':'-времена,времени',
      'example':''
    },
    {
      'level':'2',
      'word':'всегда',
      'sound':'fsigda',
      'meaning':'always',
      'class':'adverb',
      'category':'time',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'всемирный',
      'sound':'fsimirnyy',
      'meaning':'all over the world',
      'class':'adjective',
      'category':'',
      'memo':'все+мир',
      'example':''
    },
    {
      'level':'5',
      'word':'вспомнить',
      'sound':'fspomnit\'',
      'meaning':'recollect',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'встать',
      'sound':'fstat\'',
      'meaning':'stand up',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'встретить',
      'sound':'fstryetit\'',
      'meaning':'meet',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'вторник',
      'sound':'ftornik',
      'meaning':'tuesday',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'week',
      'example':''
    },
    {
      'level':'3',
      'word':'второй',
      'sound':'ftaroy',
      'meaning':'sencond',
      'class':'adjective',
      'category':'ordinal',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'входить',
      'sound':'vhadit\'',
      'meaning':'come in',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'motion verbs',
      'example':''
    },
    {
      'level':'2',
      'word':'вчера',
      'sound':'fchera',
      'meaning':'yesterday',
      'class':'noun\(f\)',
      'category':'time',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'выбрать',
      'sound':'vybrat\'',
      'meaning':'elect',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'вывести',
      'sound':'vyvest\'',
      'meaning':'withdraw',
      'class':'verb\(e\)',
      'category':'',
      'memo':'вы+вести',
      'example':''
    },
    {
      'level':'4',
      'word':'выйти',
      'sound':'viyti',
      'meaning':'get out',
      'class':'verb\(e\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'выписать',
      'sound':'vypisat\'',
      'meaning':'quote',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'высокий',
      'sound':'vysokyy',
      'meaning':'high',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'высоко',
      'sound':'vysako',
      'meaning':'highly',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'вытирать',
      'sound':'vytirat\'',
      'meaning':'wipe',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'выходить',
      'sound':'vykhodit\'',
      'meaning':'get off',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'газета',
      'sound':'gazeta',
      'meaning':'newspaper',
      'class':'noun\(f\)',
      'category':'life',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'героиня',
      'sound':'geroinya',
      'meaning':'heroine',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'герой',
      'sound':'geroy',
      'meaning':'hero',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'гестапо',
      'sound':'gestapo',
      'meaning':'gestapo',
      'class':'noun\(\)',
      'category':'history',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'гибель',
      'sound':'gibel\'',
      'meaning':'ruin',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'главный',
      'sound':'glavnyy',
      'meaning':'main chief',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'глаз',
      'sound':'glaz',
      'meaning':'eye',
      'class':'noun\(m\)',
      'category':'human body',
      'memo':'generally plural ->глаза',
      'example':''
    },
    {
      'level':'2',
      'word':'говорить',
      'sound':'govorit\'',
      'meaning':'speak',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'also.. say\/talk\/tell',
      'example':''
    },
    {
      'level':'2',
      'word':'год',
      'sound':'got',
      'meaning':'year',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'-года,лет',
      'example':''
    },
    {
      'level':'3',
      'word':'голова',
      'sound':'galava',
      'meaning':'head',
      'class':'noun\(f\)',
      'category':'human body',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'гореть',
      'sound':'garet\'',
      'meaning':'burn',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'город',
      'sound':'gorat',
      'meaning':'city',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'городок',
      'sound':'goradok',
      'meaning':'town',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'господин',
      'sound':'gospodin',
      'meaning':'Mr.',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'госпожа',
      'sound':'gospozha',
      'meaning':'Mrs.',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'гость',
      'sound':'goct\'',
      'meaning':'guest',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'готов',
      'sound':'gatof',
      'meaning':'ready',
      'class':'adjective\(s\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'готовый',
      'sound':'gotovyy',
      'meaning':'ready',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'гражданин',
      'sound':'grazhdanin',
      'meaning':'citizen',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'гриб',
      'sound':'grip',
      'meaning':'mushroom',
      'class':'noun\(m\)',
      'category':'',
      'memo':'generally plural',
      'example':''
    },
    {
      'level':'4',
      'word':'громко',
      'sound':'gromka',
      'meaning':'loud',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'группа',
      'sound':'gruppa',
      'meaning':'group',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'гулять',
      'sound':'gulyat\'',
      'meaning':'walk',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'1',
      'word':'да',
      'sound':'da',
      'meaning':'yes',
      'class':'particle',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'давать',
      'sound':'davat\'',
      'meaning':'give',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'давно',
      'sound':'davno',
      'meaning':'long ago',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'даже',
      'sound':'dazhe',
      'meaning':'even',
      'class':'particle',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'далеко',
      'sound':'daleko',
      'meaning':'far away',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'дарить',
      'sound':'darit\'',
      'meaning':'give grant',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дать',
      'sound':'dat\'',
      'meaning':'give',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'дача',
      'sound':'dacha',
      'meaning':'dacha',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'два',
      'sound':'dva',
      'meaning':'two',
      'class':'',
      'category':'number',
      'memo':'with m/n noun',
      'example':''
    },
    {
      'level':'2',
      'word':'две',
      'sound':'dve',
      'meaning':'two',
      'class':'',
      'category':'number',
      'memo':'with f noun',
      'example':''
    },
    {
      'level':'3',
      'word':'дверь',
      'sound':'dver\'',
      'meaning':'door',
      'class':'noun\(f\)',
      'category':'furniture',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'двое',
      'sound':'dvoye',
      'meaning':'two',
      'class':'',
      'category':'number',
      'memo':'with p noun',
      'example':''
    },
    {
      'level':'4',
      'word':'двор',
      'sound':'dvor',
      'meaning':'yard',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'двухэтажный',
      'sound':'dvukhetazhnyy',
      'meaning':'two-stories',
      'class':'adjective',
      'category':'',
      'memo':'дву+хэтаж',
      'example':''
    },
    {
      'level':'3',
      'word':'девочка',
      'sound':'devochka',
      'meaning':'girl',
      'class':'noun\(f\)',
      'category':'',
      'memo':'younger than девушка',
      'example':''
    },
    {
      'level':'3',
      'word':'девушка',
      'sound':'devushka',
      'meaning':'girl',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дед',
      'sound':'ded',
      'meaning':'grandfather',
      'class':'noun\(m\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дедушка',
      'sound':'dedushka',
      'meaning':'grandfather',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'декабрь',
      'sound':'dekabr\'',
      'meaning':'December',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'month',
      'example':''
    },
    {
      'level':'2',
      'word':'делать',
      'sound':'delat\'',
      'meaning':'do',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дело',
      'sound':'dela',
      'meaning':'business matter thing',
      'class':'noun\(n\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'день',
      'sound':'den\'',
      'meaning':'day',
      'class':'noun\(m\)',
      'category':'time',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'денег',
      'sound':'deneg',
      'meaning':'money',
      'class':'noun\(n\)',
      'category':'life',
      'memo':'generraly prular->деньги',
      'example':''
    },
    {
      'level':'3',
      'word':'деревня',
      'sound':'derevnya',
      'meaning':'village',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дерево',
      'sound':'derevo',
      'meaning':'tree',
      'class':'noun\(n\)',
      'category':'nature',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'деревянный',
      'sound':'derevyannyy',
      'meaning':'wooden',
      'class':'adjective',
      'category':'',
      'memo':'деревня',
      'example':''
    },
    {
      'level':'4',
      'word':'держать',
      'sound':'derzhat\'',
      'meaning':'hold',
      'class':'verb\(Ⅱ\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дети',
      'sound':'deti',
      'meaning':'children',
      'class':'noun\(p\)',
      'category':'',
      'memo':'plural only',
      'example':''
    },
    {
      'level':'4',
      'word':'диктант',
      'sound':'diktant',
      'meaning':'dictation',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'диктовать',
      'sound':'diktovat\'',
      'meaning':'dictate',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'директор',
      'sound':'direktar',
      'meaning':'director',
      'class':'noun\(m\)',
      'category':'job',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'дирижиравоть',
      'sound':'dirizhirovat\'',
      'meaning':'conduct',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'дно',
      'sound':'dno',
      'meaning':'bottom',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'до',
      'sound':'da',
      'meaning':'to for before with into',
      'class':'preposition',
      'category':'',
      'memo':'rq.accusative case',
      'example':''
    },
    {
      'level':'3',
      'word':'добрый',
      'sound':'dobryy',
      'meaning':'good',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'доволен',
      'sound':'dovolen',
      'meaning':'good',
      'class':'adjective\(s\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'довольно',
      'sound':'dovol\'na',
      'meaning':'pretty quite',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'довольный',
      'sound':'dovolinyy',
      'meaning':'satisfied',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дождь',
      'sound':'dozhd\'',
      'meaning':'rain',
      'class':'noun\(m\)',
      'category':'weather',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'долго',
      'sound':'dolga',
      'meaning':'a long while',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'должен',
      'sound':'dolzhen',
      'meaning':'must',
      'class':'auxiliary verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'дом',
      'sound':'dom',
      'meaning':'home',
      'class':'noun\(m\)',
      'category':'word',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'дома',
      'sound':'doma',
      'meaning':'at home',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'домик',
      'sound':'domik',
      'meaning':'lodge',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'5',
      'word':'дом-музей',
      'sound':'dom-muzey',
      'meaning':'house-museum',
      'class':'noun\(n\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'домой',
      'sound':'domoy',
      'meaning':'homeward',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дорога',
      'sound':'doroga',
      'meaning':'road',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дорогой',
      'sound':'dorogoy',
      'meaning':'expensive',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'достойный',
      'sound':'dostoynyy',
      'meaning':'worthy',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дочка',
      'sound':'dochka',
      'meaning':'daughter',
      'class':'noun\(f\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дочь',
      'sound':'doch\'',
      'meaning':'daughter',
      'class':'noun\(f\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'друг',
      'sound':'druk',
      'meaning':'friend',
      'class':'noun\(m\)',
      'category':'',
      'memo':'plural ->друзья',
      'example':''
    },
    {
      'level':'3',
      'word':'другой',
      'sound':'drugay',
      'meaning':'other',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'думать',
      'sound':'dumat\'',
      'meaning':'think',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'дядя',
      'sound':'dyadya',
      'meaning':'uncle',
      'class':'noun\(m\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'его',
      'sound':'yevo',
      'meaning':'his its',
      'class':'pronoun',
      'category':'',
      'memo':'demonstrative pronoun',
      'example':''
    },
    {
      'level':'2',
      'word':'её',
      'sound':'yeyo',
      'meaning':'her',
      'class':'pronoun',
      'category':'',
      'memo':'demonstrative pronoun',
      'example':''
    },
    {
      'level':'4',
      'word':'ежедневно',
      'sound':'yezhednevno',
      'meaning':'daily',
      'class':'adverb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'ездить',
      'sound':'yezdit\'',
      'meaning':'ride drive',
      'class':'verb\(e\)',
      'category':'',
      'memo':'motion verbs',
      'example':''
    },
    {
      'level':'4',
      'word':'елка(ёлка)',
      'sound':'yolka',
      'meaning':'Christmas tree',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'если',
      'sound':'yesli',
      'meaning':'if',
      'class':'conjunction',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'есть',
      'sound':'yest\'',
      'meaning':'there is',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'2',
      'word':'есть',
      'sound':'yest\'',
      'meaning':'eat',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-ем,ешь',
      'example':''
    },
    {
      'level':'3',
      'word':'ехать',
      'sound':'yekhat\'',
      'meaning':'go travel',
      'class':'verb\(e\)',
      'category':'',
      'memo':'motion verbs',
      'example':''
    },
    {
      'level':'3',
      'word':'ещё',
      'sound':'yeshcho',
      'meaning':'more yet',
      'class':'\(n\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'жалка',
      'sound':'zhalka',
      'meaning':'pathetic',
      'class':'adjective',
      'category':'',
      'memo':'rq.accusative case',
      'example':''
    },
    {
      'level':'3',
      'word':'жаль',
      'sound':'zhal\'',
      'meaning':'pity',
      'class':'adverb',
      'category':'',
      'memo':'phrase',
      'example':''
    },
    {
      'level':'3',
      'word':'жарко',
      'sound':'zhalka',
      'meaning':'hot',
      'class':'adverb',
      'category':'weather',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'ждать',
      'sound':'zhdat\'',
      'meaning':'wait',
      'class':'verb\(e\)',
      'category':'',
      'memo':'-жду,ждёшь',
      'example':''
    },
    {
      'level':'2',
      'word':'же',
      'sound':'zhe',
      'meaning':'the same',
      'class':'particle',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'желать',
      'sound':'zhelat\'',
      'meaning':'wish',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'жена',
      'sound':'zhena',
      'meaning':'wife',
      'class':'noun\(f\)',
      'category':'family',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'женский',
      'sound':'zhenskiy',
      'meaning':'feminine',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'4',
      'word':'женщина',
      'sound':'zhenshchina',
      'meaning':'woman',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'живой',
      'sound':'zhivoy',
      'meaning':'alive lively',
      'class':'adjective',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'жизнь',
      'sound':'zhizn\'',
      'meaning':'life',
      'class':'noun\(f\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'жить',
      'sound':'zhit\'',
      'meaning':'live',
      'class':'verb',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'журнал',
      'sound':'zhurnal',
      'meaning':'magazine',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    },
    {
      'level':'3',
      'word':'журналист',
      'sound':'zhurnalist',
      'meaning':'journalist',
      'class':'noun\(m\)',
      'category':'',
      'memo':'',
      'example':''
    }
  ]
  
  var tableCap = $('<h1 />').text('RussianVocabs');
  $('body').prepend(tableCap);
  var theadSetter = function(){
    var tr = $('<tr />');
    var len = theadElements.length;
    for(var i=0;i<len;i++){
      var td = $('<td />');
      td.text(theadElements[i]);
      tr.append(td);
    }
    thead.append(tr);
  }
  theadSetter();
  
  var tr,td,len,lenj,key,text;
  var tbodySetter = function(){
    len = vocabs.length;
    for(var i=0;i<len;i++){
      tr = $('<tr />'),lenj = theadElements.length;
      for(var j=0;j<lenj;j++){
        td = $('<td />'),key = theadElements[j];
        text = vocabs[i][key];
        if(key=='sound'){text='('+ text +')'}
        td.text(text);
        if(key=='word'){td.css('font-weight','bold');}
        tr.append(td);
      }
      tbody.append(tr);
    }
  }
  tbodySetter();
  
  var colLen = theadElements.length;
  for(var i=0;i<colLen;i++){
    colArray.push(i);
  }
  
  var table = vocabsTable.dataTable( {
    paginate: false,
    dom:'fRTCti',
    colReorder: {
      order: colArray
    },
    colVis:{
      align:'left',
      ovetlayFade:'400',
      showAll:'show all'
    },
    tableTools:{
      aButtons:['select_none'],
      sRowSelect:'multi'
    },
    responsive:{
    }
  });
  new $.fn.dataTable.FixedHeader( table );
  $('div#datatable_filter label input').on('keypress,keyup', function(){
  	$('div.fixedHeader').remove();
  	new $.fn.dataTable.FixedHeader( table );
  });
  var colResetButton = $('<a />').text('Reorder column');
  var colReset = $('<div />').attr({'id':'colReset','class':'responsiveDiv'}).html(colResetButton);
  
  $('div .DTTT_container').before(colReset);
  var colReorder = new $.fn.dataTable.ColReorder( table, {
        "aiOrder": colArray
  } );

    $('#colReset').click( function () {
        colReorder.fnReset();
        return false;
    } );    
  $('#colorSwitcher').click(function(e){
    e.preventDefault();
    chuck(bgImgIndex);
    do{
      randomIndex = Math.round(Math.random()*bgImgAry.length-0.5); 
    }while(bgImgIndex==randomIndex);
    bgImgIndex=randomIndex;
    $('body').css('background-image','url('+ bgImgAry[bgImgIndex] +')');
  });
  
  var ajaxError = function(e){
    console.log(e);
  }
  var ajaxSuccess = function(json){
    console.log(json);
  }
  
  //$.ajax({
  //  type:'GET',
  //  url:'vocab1.json',
  //  dataType:'json',
  //  success:ajaxSuccess,
  //  error:ajaxError
  //});
});